CarRentingWebClient/Controllers/RentingTransactionsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using BusinessObjects;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;
using CarRentingWebClient.AccessAPIs.Interfaces;
using BusinessObjects.DTOs;
using AutoMapper;

namespace CarRentingWebClient.Controllers;

[Authorize(Roles = "Admin")]
[Route("Admin/{controller}/{action=Index}/{id?}")]
public class RentingTransactionsController : Controller
{
    private readonly IRentingTransactionAPIs _transactionAPIs;
    private readonly IRentingDetailAPIs _detailAPIs;
    private readonly ICustomerAPIs _customerAPIs;
    private readonly IMapper _mapper;
    private readonly ISession session;

    public RentingTransactionsController(IRentingTransactionAPIs transactionAPIs, 
                                                IRentingDetailAPIs detailAPIs,
                                                ICustomerAPIs customerAPIs,
                                                IMapper mapper,
                                                IHttpContextAccessor httpContext)
    {
        _transactionAPIs = transactionAPIs;
        _detailAPIs = detailAPIs;
        _customerAPIs = customerAPIs;
        _mapper = mapper;
        session = httpContext.HttpContext!.Session;
    }

    [TempData]
    public string? Message { get; set; }
    [TempData]
    public DateTime? StartDate { get; set; }
    [TempData]
    public DateTime? EndDate { get; set; }

    // GET: Admin/RentingTransactions
    [ActionName("TransactionHistory")]
    public async Task<IActionResult> Index()
    {
        ViewData["username"] = HttpContext.User.Claims.Where(x => x.Type == ClaimTypes.Name).FirstOrDefault()!.Value;
        ViewData["userid"] = HttpContext.User.Claims.Where(x => x.Type == ClaimTypes.NameIdentifier).FirstOrDefault()!.Value;
        ViewData["token"] = session.GetString("token");
        return View("TransactionList", await _transactionAPIs.GetRentingTransactionsAsync());
        //return View("TransactionList");
    }

    // GET: Admin/RentingTransactions/TransactionDetails?transactionId=5
    [ActionName("TransactionDetails")]
    public async Task<IActionResult> Details(int? transactionId)
    {

        ViewData["username"] = HttpContext.User.Claims.Where(x => x.Type == ClaimTypes.Name).FirstOrDefault()!.Value;
        ViewData["userid"] = HttpContext.User.Claims.Where(x => x.Type == ClaimTypes.NameIdentifier).FirstOrDefault()!.Value;
        if (transactionId == null)
        {
            return NotFound();
        }

        var rentingDetail = await _detailAPIs.GetRentingDetailsByTransactionAsync(transactionId.Value);
        //if (rentingDetail == null || rentingDetail.Count == 0)
        //{
        //    return NotFound();
        //}

        return View("TransactionDetails", rentingDetail);
    }

    // GET: Admin/RentingTransactions/Edit/5
    public async Task<IActionResult> Edit(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var rentingTransaction = await _transactionAPIs.GetRentingTransactionAsync(id.Value);
        if (rentingTransaction == null)
        {
            return NotFound();
        }
        var customers = await _customerAPIs.GetCustomersAsync();
        ViewData["CustomerId"] = new SelectList(customers, "CustomerId", "CustomerName", rentingTransaction.CustomerId);
        ViewData["Message"] = Message;
        return View(rentingTransaction);
    }

    // POST: Admin/RentingTransactions/Edit/5
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, RentingCreateDTO rentingTransaction)
    {
        if ((await _transactionAPIs.GetRentingTransactionAsync(id)) == null)
        {
            return NotFound();
        }

        if (ModelState.IsValid)
        {
            try
            {
                await _transactionAPIs.UpdateRentingTransactionAsync(id, rentingTransaction);
            }
            catch (Exception ex)
            {
                Message = ex.Message;
            }
            return RedirectToAction("TransactionHistory");
        }
        var customers = await _customerAPIs.GetCustomersAsync();
        ViewData["CustomerId"] = new SelectList(customers, "CustomerId", "CustomerName", rentingTransaction.CustomerId);
        ViewData["Message"] = Message;
        return View(_mapper.Map<RentingTransaction>(rentingTransaction));
    }

    // GET: Admin/RentingTransactions/Delete/5
    public async Task<IActionResult> Delete(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var rentingTransaction = await _transactionAPIs.GetRentingTransactionAsync(id.Value);
        if (rentingTransaction == null)
        {
            return NotFound();
        }

        return View(rentingTransaction);
    }

    // POST: Admin/RentingTransactions/Delete/5
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
        var rentingTransaction = await _transactionAPIs.GetRentingTransactionAsync(id);
        if (rentingTransaction != null)
        {
            try
            {
                await _transactionAPIs.DeleteRentingTransactionAsync(id);
            }
            catch (Exception ex)
            {
                Message = ex.Message;
                return RedirectToAction(nameof(Delete), rentingTransaction);
            }
        }
        return RedirectToAction("TransactionHistory");
    }

    [HttpGet]
    public async Task<IActionResult> Search(DateTime startDate, DateTime endDate)
    {
        ViewData["username"] = HttpContext.User.Claims
            .Where(x => x.Type == ClaimTypes.Name)
            .FirstOrDefault()!.Value;

        var carRentalList = new List<RentingTransaction>();
        if (startDate != DateTime.MinValue && endDate != DateTime.MinValue)
        {
            carRentalList = (await _transactionAPIs.GetRentingTransactionsAsync())
                    .Where(x => x.RentingDate >= startDate && x.RentingDate <= endDate)
                    .OrderByDescending(x => x.RentingDate)
                    .ToList(); ;
            StartDate = startDate;
            EndDate = endDate;
            ViewData["startDate"] = StartDate;
            ViewData["endDate"] = EndDate;
        }

        return View("TransactionList", carRentalList);
    }
}

CarRentingWebClient/Views/RentingTransactions/Delete.cshtml
@model BusinessObjects.RentingTransaction

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Renting Transaction</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RentingDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RentingDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TotalPrice)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TotalPrice)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RentingStatus)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RentingStatus)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Customer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Customer.Email)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="RentingTransationId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="TransactionHistory">Back to List</a>
    </form>
</div>

CarRentingWebClient/Views/RentingTransactions/Edit.cshtml
@model BusinessObjects.RentingTransaction

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Renting Transaction</h4>
<div>
    <a asp-action="TransactionHistory">Back to List</a>
</div>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="RentingTransationId" />
            <div class="form-group mb-3">
                <label asp-for="RentingDate" class="control-label"></label>
                <input asp-for="RentingDate" class="form-control" />
                <span asp-validation-for="RentingDate" class="text-danger"></span>
            </div>
            <div class="form-group mb-3">
                <label asp-for="TotalPrice" class="control-label"></label>
                <input asp-for="TotalPrice" class="form-control disabled" />
                <span asp-validation-for="TotalPrice" class="text-danger"></span>
            </div>
            <div class="form-group mb-3">
                <label asp-for="CustomerId" class="control-label">Customer Name</label>
                <select asp-for="CustomerId" class="form-control" asp-items="ViewBag.CustomerId"></select>
                <span asp-validation-for="CustomerId" class="text-danger"></span>
            </div>
            <div class="form-group mb-3">
                <label asp-for="RentingStatus" class="control-label"></label>
                <input asp-for="RentingStatus" class="form-control" />
                <span asp-validation-for="RentingStatus" class="text-danger"></span>
            </div>
            <div class="form-group mb-3">
                <input type="submit" value="Save" class="btn btn-light btn-outline-primary col-12" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CarRentingWebClient/Views/RentingTransactions/TransactionList.cshtml
@model IEnumerable<BusinessObjects.RentingTransaction>

@{
    ViewData["Title"] = "Transaction History";
}

<h1>Transaction History</h1>

<hr />
@* Search *@
<div class="row">
    <form method="get" asp-controller="RentingTransactions" asp-action="Search" class="col-10">
        <span class="me-3">From date</span>
        <input class="me-3" value="@ViewBag.startDate" name="startDate" type="date" />
        <span class="me-3">To date</span>
        <input class="me-3" value="@ViewBag.endDate" name="endDate" type="date" />
        <input type="submit" value="Search" class="btn btn-dark btn-outline-light me-4" /> |
        <a asp-action="TransactionHistory" class="ms-4">Back to full list</a>
    </form>
</div>
<br />
@* End search *@

<p>
    <a asp-controller="Admin" asp-action="Renting" class="btn btn-secondary">Make New Transaction</a>
</p>
<table class="table" id="transaction-table">
    <thead>
        <tr>
            <th>
                Renting Date
            </th>
            <th>
                Customer
            </th>
            <th>
                Total Price
            </th>
            <th>
                Renting Status
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.RentingDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Customer.CustomerName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TotalPrice)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.RentingStatus)
                </td>
                <td>
                    <a asp-action="TransactionDetails" asp-route-transactionId="@item.RentingTransationId">Details</a>
                    <a asp-action="Edit" asp-route-id="@item.RentingTransationId">| Edit</a>
                    <a asp-action="Delete" asp-route-id="@item.RentingTransationId">| Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>
<div style="display:none">
    <input id="token" name="token" value="@ViewData["token"]" />
</div>